### ISSUE TITLE
Autocomplete doesn't expand/understand struct instances

### ISSUE THREAD

**Issue by oziphantom** [sjPlot/Relaunch64#24]
Given 

sScoreValues .struct
digit6 .byte ?
digit5 .byte ?
digit4 .byte ?
digit3 .byte ?
digit2 .byte ?
digit1 .byte ?
.ends

Score .dstruct sScoreValues
HiScore .dstruct sScoreValues

The Auto Complete will only see Score and HiScore not
Score.digit6 etc 

TASS mode.

**Comment by soci64** [comment]
Known limitation. Complexity should stop somewhere before I reimplement these assemblers in the editor ;)

Otherwise we're quickly approaching things like I've created an alias with "=" to this (sub)struct/label and it does not show it's members correctly. Or a struct was defined in another scope and not where it's instantiated like ".dstruct aa.bb.cc.stuff_struct". Or it was defined from another file, included somewhere. Etc, etc. it's even possible to create loops in the scope "tree" if I try hard enough ;-)

So you've reached the limits of this simple linear parser in the editor. Sorry. On the bright side this only means one thing, you're beyond what most people do with it ;-)

**Comment by oziphantom** [comment]
There isn't just a patch that when you hit dstruct it takes the label and adds it to the "table" as a type X?

**Comment by soci64** [comment]
There's no such table, just a list of scopes with list of labels, created/deleted on scope entry/exit on the fly while parsing top to bottom. Stuff is not kept around permanently, even if the struct as a label might be still available it's members are long gone by the time dstruct is encountered.

Anyway it would be rather complex and still limited. I have something other in mind which could handle complex stuff better, but not sure yet what the others think about that. It would change operation quite a bit, and some parts I don't plan to code myself.

**Comment by oziphantom** [comment]
Yeah if that is what it is doing, not going to work....

**Comment by oziphantom** [comment]
As a halfway house could the labels in the structs be added to the AutoComplete list?
